### ISSUE TITLE
Have you considered using HomeKit protocol/integration for HA to control Sensi?

### ISSUE THREAD

**Issue by dig12345** [iprak/sensi#11]
Hey this looks like a really cool project and excited to see HA integration for sensi which is strangely lacking. I've seen reports of ppl connecting the sensi to HA using HomeKit protocol.  I was going to give it a shot when I found this project and now I'm curious if y'all have tried that path vs having to reverse engineer the App? Does HomeKit option no longer work or have limited features etc

PS I'll def try installing this on my HA. Thanks for you work!

**Comment by iprak** [comment]
I remember trying it and was unable to integrate using Homekit. I could not detect the thermostat via zeroconfig; it might have been my thermostat.

**Comment by stleusc** [comment]
HA supports Sensi via HomeKit out-of-the-box. However, I was only able to add ONE out of my 4 Sensi via HomeKit.
So technically using HomeKit here would not make sense since it would only replicate what already can be done in HA.

I DO love this addon however....

**Comment by iprak** [comment]
I have 2 similar looking Sensi thermostats. My older Sensi thermostat reports itself as "Sensi Classic" while the newer one as "Sensi Classic with HomeKit". So it could be a thermostat model thing. But neither of them were auto detected.  ¯\\_(ツ)_/¯

**Comment by iprak** [comment]
Sorry, at this point I have no plans on using HomeKit.
