### ISSUE TITLE
Setup fail on 1.1.2 update using HACS

### ISSUE THREAD

**Issue by jowser7** [iprak/sensi#15]
Used update button, then restarted home assistant with Developer tools. After seeing the error, also restarted HA with system menu with same result.
Logger: homeassistant.setup
Source: setup.py:213
First occurred: 9:56:19 PM (1 occurrences)
Last logged: 9:56:19 PM

Setup failed for custom integration sensi: Unable to import component: cannot import name 'StrEnum' from 'enum' (/usr/local/lib/python3.10/enum.py)

**Comment by iprak** [comment]
What is your HomeAssistant version?

**Comment by iprak** [comment]
I think you are on an older HomeAssistant version, HomeAssistant  updated to Python 3.11 a few releases ago. The error message refers to 3.10.

**Comment by jowser7** [comment]
Home Assistant 2023.2.5, Frontend 20230202.0
I'm running the Docker core version. I'll look at updating my system and update here with my results.
I had a hunch it was something like this, however things were running fine up until I pressed the update. I had previously 1.1.1, but did't have that error. Now upon trying to revert, I couldn't install 1.1.1 either.

**Comment by jowser7** [comment]
All fixed by updating to latest release of HA 2023.9.2.  Just a warning for others, you'll need to recreate the entities as they changed format. Thanks iprak for the maintenance.

**Comment by iprak** [comment]
Sorry about id change , it did in 1.1.1. I mentioned it in the Readme. Unfortunately I got it wrong and might change again.
