### ISSUE TITLE
Temperature sensor showing wrong units in 1.2.0 

### ISSUE THREAD

**Issue by goguda** [iprak/sensi#17]
<img width="335" alt="Screenshot 2023-09-17 at 9 01 16 PM" src="https://github.com/iprak/sensi/assets/26887502/93752984-5523-497f-87e3-3e61bfc5892a">

Should be 22 degrees C, if I switch to C in settings it shows as -6C (which is wrong)

**Comment by iprak** [comment]
That seems wrong. What unit is your thermostat set to display?

**Comment by goguda** [comment]
> That seems wrong. What unit is your thermostat set to display?

The actual thermostat setting is set to C, home assistant is defaulting to F on 1.2.0. If I change it to C manually it shows as -6C. You can see above too in the Thermostat section it's reading 22C, so it's just the temperature sensor alone it seems.

Was working fine before the update.

**Comment by goguda** [comment]
<img width="337" alt="Screenshot 2023-09-18 at 5 26 06 PM" src="https://github.com/iprak/sensi/assets/26887502/dd3e312d-6eb4-484a-8115-2806d9f6028d">

**Comment by iprak** [comment]
This should be fixed in v1.2.1

**Comment by goguda** [comment]
Can confirm fixed, thank you so much!
