### ISSUE TITLE
Aux heat

### ISSUE THREAD

**Issue by spydazcomputers** [iprak/sensi#21]
Is it possible to add an auxiliary heat mode option.?

**Comment by iprak** [comment]
Support for aux heat has been added in https://github.com/iprak/sensi/pull/25. 

This however is not a complete solution. The default Climate card provided via HomeAssistant does not seem to support "auxillary" heat as an option, meaning one doesn't see or set "aux" in the available options. This shortcoming has been mentioned here - https://github.com/home-assistant/frontend/issues/14881. There might be other custom party cards which allow enabling aux state.
