### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by calimansi** [iprak/sensi#27]
Hi,

With some problems I'm seeing, I just tried re-installing the addon.  I can't login anymore.  It says invalid credentials.  I am using the credentials to log into the mobile app.  I'm stuck.

**Comment by iprak** [comment]
You can try enabling logging (https://github.com/iprak/sensi/issues/3#issuecomment-1528479764) which tell something.

**Comment by calimansi** [comment]
I can't get the integration to pop up since I can't add it.  Do you know how I can enable debug logging without the integration being used?

**Comment by iprak** [comment]
You can try setting debug/warn level as the default. This might tell why integration is failing.

```
logger:
  default: warn
```

**Comment by srcochran** [comment]
I'm having the same problem, and the logs don't provide much detail:

Logger: homeassistant.config_entries
Source: config_entries.py:430
First occurred: 9:33:59 PM (1 occurrences)
Last logged: 9:33:59 PM

Config entry 'Sensi Thermostat' for sensi integration could not authenticate: Invalid login credentials

**Comment by vshijiav** [comment]
Yes right now it is rejecting credentials, all the entities become unusable

**Comment by vshijiav** [comment]
I have tried create a new sensi account and its still rejecting me login

**Comment by BillBlight** [comment]
Same here can't log in, logs not helpful ..

**Comment by DigitalKloc** [comment]
I'm having the same issue. When I hit Reconfigure, I only get a single line and it doesn't say if it's for username or password. Setting the logger to warn didn't give any additional info that I can see.

**Comment by Xylobol** [comment]
Getting this as well. Single field to reconfigure.

**Comment by dannyboymed** [comment]
Same here, a one field credential box that doesn't do anything. Seems like something may have changed and broke it for everybody.

**Comment by derousse** [comment]
I'm also having the same issue.  Hitting Reconfigure only gives one prompt and neither the login or password is accepted successfully.

**Comment by iprak** [comment]
It seems that the authentication at Sensi end has changed. This integration was based on sort of reverse engineering the Android app. I just might have been lucky till now.

At this point, I don't know what has changed and my usual attempts have not been successful.

**Comment by LAHA2** [comment]
For what it's worth, I'm unable to login to the Sensi Multiple Thermostat Manager website from a PC. I believe I could previously view my thermostats from this URL. Perhaps others can confirm? 

But same problem - upon HA reboot today, no longer recognizes credentials.

**Comment by LAHA2** [comment]
Same issue - frustrating that Sensi provides support for Alexa, Google, SmartThings....but not HA

**Comment by venterlin** [comment]
Oh well, stopped working on my end around 8:30PM EST yesterday. This is why cloud devices suck so bad.

So I'm back using data from HomeKit, which blows because there's no Humidity data available.

Anyhow, thanks to the dev of this great integration. You provided a fantastic integration, especially considering the challenge of proprietary crap you had to unravel to get it working.

**Comment by LAHA2** [comment]
Mind if I ask what HomeKit is with regard to Sensi thermostats?

**Comment by adamhorsburgh** [comment]
Having the same problem as of yesterday.

**Comment by laurenslo** [comment]
Dang. 😟

**Comment by pkolbus** [comment]
@iprak Disappointed that this isn’t working anymore, but still thankful for your work on this integration over the years.

**Comment by iprak** [comment]
This should be fixed now

**Comment by DigitalKloc** [comment]
Thank you, @iprak. The latest update is working for me! Having the aux_heat attribute has been fantastic to have, especially during the last week when it was too cold for my heat pump. My aux heat is a heating oil furnace so being able to track how long it's been running lets me figure how much heating oil I have left.

**Comment by dannyboymed** [comment]
All fixed up! Thank you.

**Comment by laurenslo** [comment]
Oh my! That was quick!! Thank you iprak!!!

**Comment by ConnorBS** [comment]
Awesome, reconnected now

**Comment by LAHA2** [comment]
Ah-mazing! And thank you!
