### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by Battlewind** [iprak/sensi#30]
I appear to have lost the readouts on the integration for my two thermostats. I have deleted and reloaded the integration, but login is not working. I changed my Sensi password and still the integration tells me I have invalid credentials. Any changes to login after this recent update?

**Comment by airxwing** [comment]
Hello, I also have the same problem. Login is not working anymore even after deleting and adding the integreation again. Anything extra or modifications we manually have to perform to make it work?

**Comment by iprak** [comment]
What is the integration version?

**Comment by airxwing** [comment]
Can't tell. I delete the one was installed and tried to add the current integration again. Once searched for the sensi integration and presented with UserName* and Password* prompt, submitting gets an error: ! Invalid credentials

**Comment by Battlewind** [comment]
> Login issues were recently addressed in version 1.2.4. Please check if you have that.

That fixed it. I found I had 1.2.3 or something and had to update it via HACS. Thank you!
