### ISSUE TITLE
"Invalid Credentials" No Longer Able To Authenticate

### ISSUE THREAD

**Issue by bperry11** [iprak/sensi#31]
Suddenly, the sensi integration is unable to authenticate. I tried to setup a new instance and still get an "invalid credentials" error. I am able to login to the sensi app with those same credentials. Maybe a auth token issue?

**Comment by iprak** [comment]
What is the version of the integration? Login issue was recently addressed in the latest release.

**Comment by bperry11** [comment]
@iprak ah ok. I see that now. Sorry, should have checked that first. Bringing in the latest update solved this issue.
