### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by Saint6822** [iprak/sensi#46]
I have successfully setup the new sensi integration with the token (at least I think) but I do not appear to have the option to add thermostat controls to my dashboard. Any suggestions? I have the following,

Sensors
- humidity
- temperature

Configuration
- Display Humidity
- Display Time
- Fan Support
- Keypad Lockout

Diagnostic
- Batery
- Max setpoint
- Min setpoint

**Comment by iprak** [comment]
You will need to add a thermostat card or custom card (see 
https://www.home-assistant.io/dashboards/thermostat/).

**Comment by Saint6822** [comment]
Sorry if I wasn't clear, the control entity is missing entirely

**Comment by iprak** [comment]
That is weird. How many entities do you see for the Sensi integration? Is there no `climate.` entity?
![image](https://github.com/iprak/sensi/assets/6459774/24cc52c8-bf0c-440f-b990-3983768a240d)

**Comment by Saint6822** [comment]
Only the ones in this screen shot.

On March 24, 2024 10:00:23 a.m. EDT, Indu Prakash ***@***.***> wrote:
>That is weird. How many entities do you see for the Sensi integration? Is there no `climate.` entity?
>![image](https://github.com/iprak/sensi/assets/6459774/24cc52c8-bf0c-440f-b990-3983768a240d)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/iprak/sensi/issues/46#issuecomment-2016818976
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- Sent from /e/OS Mail.

**Comment by Saint6822** [comment]
Sorry wrong shot

On March 24, 2024 10:00:23 a.m. EDT, Indu Prakash ***@***.***> wrote:
>That is weird. How many entities do you see for the Sensi integration? Is there no `climate.` entity?
>![image](https://github.com/iprak/sensi/assets/6459774/24cc52c8-bf0c-440f-b990-3983768a240d)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/iprak/sensi/issues/46#issuecomment-2016818976
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- Sent from /e/OS Mail.

**Comment by iprak** [comment]
Can you include a screenshot of the middle column of device integration ?

**Comment by Saint6822** [comment]
Sorry about the quality snapped on my laptop

**Comment by Saint6822** [comment]
Or did you mean this?

**Comment by iprak** [comment]
I am not seeing any screenshot ?

**Comment by Saint6822** [comment]
I forgot to mention it did work before the need to switch to using the token

**Comment by iprak** [comment]
I wonder if the token is incorrect. Are the visible Sensors unavailable ?

**Comment by Saint6822** [comment]
The sensors are picking up the correct readings. It is odd

On March 24, 2024 12:13:53 p.m. EDT, Indu Prakash ***@***.***> wrote:
>I wonder if the token is incorrect. Are the visible Sensors unavailable ?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/iprak/sensi/issues/46#issuecomment-2016857426
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- Sent from /e/OS Mail.

**Comment by iprak** [comment]
I would check under  `Settings > Devices & services > Entities` if there is something starting with climate.sensi and enable debug logging (https://github.com/iprak/sensi/issues/46#issuecomment-2016818976).

**Comment by Saint6822** [comment]
Will do as soon as I get home

On March 24, 2024 1:43:51 p.m. EDT, Indu Prakash ***@***.***> wrote:
>I would check under  `Settings > Devices & services > Entities` if there is something starting with climate.sensi and enable debug logging (https://github.com/iprak/sensi/issues/46#issuecomment-2016818976).
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/iprak/sensi/issues/46#issuecomment-2016883017
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- Sent from /e/OS Mail.

**Comment by Saint6822** [comment]
No climate.sensi. I have tried removing everything. Restarting Home Assistant and adding the add-on again. Still does show.

**Comment by iprak** [comment]
I would enable debug logging for the integration, restart and check the log.

**Comment by Saint6822** [comment]
There definitely is an issue , sorry I'm have no idea what i am looking at, I attached the whole log.
2024-03-24 21:26:31.348 ERROR (MainThread) [homeassistant.components.climate] Error while setting up sensi platform for climate
[home-assistant.log](https://github.com/iprak/sensi/files/14737328/home-assistant.log)

**Comment by iprak** [comment]
What is the version of your HomeAssistant ?

**Comment by iprak** [comment]
Climate entity setup fails when accessing ClimateEntityFeature.TURN_ON. TURN_ON was introduced in HomeAssistant about 2 months ago ([commit](https://github.com/home-assistant/core/commit/bc720b48b476d2fa1ad754166d6aca72e0d180cf)).

**Comment by Saint6822** [comment]
Running under CasaOS in a container, I will try to update and get back to you.
Core 2023.11.3
Frontend 20231030.2

**Comment by Saint6822** [comment]
Thanks for you help! though I had issues updating, I just blew the Home Assistant away copied my config folder back in (minus the sensi component), reinstalled your integration  and voila it worked!! Something was obviously corrupt with my home assistant container.

**Comment by iprak** [comment]
I am glad it worked out. Now I recall that HomeAssiatant was generating a deprecation warning or something and suggested using that value.
