### ISSUE TITLE
Unable to log in 

### ISSUE THREAD

**Issue by jmajerus** [iprak/sensi#47]
I've unsuccessfully tried using your updated instructions, which are not entirely clear. 

When trying to re-install the Home Assistant integration, I get the following prompt:

"Set up Sensi integration. Login with yout (sic) mobile app credentials."
Username: _______________________
Password: ________________________

Can you please be more specific about what goes where? I've tried using my email address in the username field with the "refresh_token" value in the password field. Alternately, if tried the "user_id" value listed in the developer tools window further down from where the refresh_token is. Neither option works.

Thanks!

**Comment by iprak** [comment]
You seem to have older version of the integration.

**Comment by nyalapoker** [comment]
I am also unable to log in.  I have done as indicated and found the refresh token, copied and pasted... and get an unexpected error. 

I am using the most recent version that is only asking me for the refresh_token

**Comment by iprak** [comment]
The HomeAssistant log should have more info. Can you paste the log?

**Comment by nyalapoker** [comment]
I need some direction as to how to do that.  But I will gladly follow instruction.Http://www.lasraicesranch.comConfidentiality NoticeThis message is intended only for the use of the individual or entity to which it is addressed and may contain information that is privileged, confidential, and exempt from disclosure under applicable law.  If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited.  If you have received this email in error, please reply immediately and delete the message.  Thank you. On Mar 27, 2024, at 4:58 AM, Indu Prakash ***@***.***> wrote:﻿
The HomeAssistant log should have more info. Can you paste the log?

**Comment by iprak** [comment]
This should help https://www.home-assistant.io/integrations/system_log/

**Comment by nyalapoker** [comment]
> This should help https://www.home-assistant.io/integrations/system_log/

2024-03-27 11:09:27.558 ERROR (MainThread) [custom_components.sensi] 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "/config/custom_components/sensi/config_flow.py", line 43, in _try_login
    await refresh_access_token(self.hass, config.refresh_token)
  File "/config/custom_components/sensi/auth.py", line 161, in refresh_access_token
    persistent_data[KEY_ACCESS_TOKEN] = result[KEY_ACCESS_TOKEN]
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment

**Comment by iprak** [comment]
This issue might be addressed by https://github.com/iprak/sensi/pull/48. I will review and merge it soon.

**Comment by nyalapoker** [comment]
> This issue might be addressed by #48. I will review and merge it soon.

With that change made error goes to this:

2024-03-27 13:05:08.292 ERROR (MainThread) [custom_components.sensi] 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "/config/custom_components/sensi/config_flow.py", line 43, in _try_login
    await refresh_access_token(self.hass, config.refresh_token)
  File "/config/custom_components/sensi/auth.py", line 161, in refresh_access_token
TypeError: 'NoneType' object does not support item assignment

**Comment by iprak** [comment]
This is the same exception at before .. at line 161.

**Comment by iprak** [comment]
I have not reviewed the merge yet.

**Comment by Adrian7654321** [comment]
I also have an issue but in my case I am getting Invalid authentification when using the refresh token. I got my refresh token in chrome as per the instruction on the right side of https://oauth.sensiapi.io/token?device=   xxxxx-xxxxxxxxx-xxxxxxxx  [redacted] 

Also I seem to get a new refresh token every time that I log in to https://manager.sensicomfort.com/  is that expected?

Logger: custom_components.sensi
Source: custom_components/sensi/auth.py:84
integration: Sensi ([documentation](https://github.com/iprak/sensi), [issues](https://github.com/iprak/sensi/issues))
First occurred: 10:00:19 PM (6 occurrences)
Last logged: 10:14:07 PM
Invalid token

**Comment by iprak** [comment]
There is a new release now.

**Comment by nyalapoker** [comment]
Thank You!  Got it working.
