### ISSUE TITLE
Websockets=12.0

### ISSUE THREAD

**Issue by jsiemonski** [iprak/sensi#53]
Updated my install and now I'm getting this error. I'm not sure what I need to install.

Setup failed for custom integration 'sensi': Requirements for sensi not found: ['websockets=12.0'].

**Comment by iprak** [comment]
How is HomeAssistant installed?

**Comment by iprak** [comment]
Hmm then I would have expected it to work. I will did more later today.

Do you have access to the custom_components folder where sensi is installed? Can you replace the =12.0 requirement in manifest.json to >=11.0.1 and restart HomeAssiatant?

**Comment by jsiemonski** [comment]
That worked!

**Comment by jcamm3** [comment]
> >=11.0.1

I also had the same issue following the recent update.  Changing the manifest.json file from =12.0 to >=11.0.1 also fixed my issue.

**Comment by iprak** [comment]
This was addressed in v1.3.9
