### ISSUE TITLE
Get status of thermostat

### ISSUE THREAD

**Issue by nienow** [iprak/sensi#60]
Hi, thank you for this integration! Is there anyway to get the current status of the thermostat (heating/cooling/idle)? I want to use the status in automations, but I didn't see any entities related to status, only the mode.

**Comment by iprak** [comment]
The Sensi entity is extends [Climate entity](https://developers.home-assistant.io/docs/core/entity/climate/) which exposes hvac_action which can provide that information. This is available as attribute on the sensi climate entity. You can use Developer tools > STATES to inspect the entity.

**Comment by nienow** [comment]
I found it, thank you!
