### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by rubernck21** [iprak/sensi#64]
So, yes, I am new to HA and all setup. I began by going to the URL provided and tried to sign in. I KINDA think I can sign in, but when i browse around, I only see the part where the site is asking me to pay for a membership. Is this a requirement? I have the app, and it works great, but not this URL.

**Comment by iprak** [comment]
You don't need to buy any membership, you went too far. Please refer to the Readme screenshots, you just need to log in to get the tokens.

**Comment by rubernck21** [comment]
Ok, IF I'm signed in, should I be able to see more for settings or profile changes...it seems like I'm signed in, but I'm not seeing anything like that, hence asking about the payment part.

TY for the quick reply.

**Comment by iprak** [comment]
You need to _navigate to https://manager.sensicomfort.com/, press F12 to launch Dev Tools, switch to Network tab, login with your credentials and grab the value of refresh_token_. I think you are simply logging in without pressing F12. F12 will launch Developer Tools which is from where the value has to be copied.

**Comment by rubernck21** [comment]
I think I got it, found the 2 sets of codes I need. It's just the site doesn't really ACT like I was signed in.  Weird.  Thank you.

As for the directions. I see it is stated that I don't have to pay for anything...wonder how I didn't notice it before.  Maybe capitalizing the whole sentence might make it jump out more.

Thank you for your help.
