### ISSUE TITLE
Fan mode not reporting correctly

### ISSUE THREAD

**Issue by christcb03** [iprak/sensi#68]
When I set the fan mode to "on" from the Sensi app, home assistant still reports the fan mode as Circulate. This is throwing off automations.

If I try to set the fan mode from home assistant, it will set to either on or auto but after a few moments home assistant again reports the fan as in Circulate mode no matter which I selected. It does appear to change in the app and on the thermostat correctly.

**Comment by iprak** [comment]
Fixed in v1.3.14
